// NPC States
REGISTER_STATE(NPC_State_Idle)
REGISTER_STATE(NPC_State_IdleForDuration)
REGISTER_STATE(NPC_State_Engage)
REGISTER_STATE(NPC_State_Attack)
REGISTER_STATE(NPC_State_Retreat)
REGISTER_STATE(NPC_State_MoveToRandomPointInZone)
REGISTER_STATE(NPC_State_WalkTowardPlayerAttack)
REGISTER_STATE(NPC_State_WalkTowardPlayerEngage)
REGISTER_STATE(NPC_State_DashingAttack)
REGISTER_STATE(NPC_State_DashingEngage)
REGISTER_STATE(NPC_State_DashingStunned)
REGISTER_STATE(NPC_State_HitNRunAttack)
REGISTER_STATE(NPC_State_HitNRunRetreat)
REGISTER_STATE(NPC_State_HitNRunEngage)
REGISTER_STATE(NPC_State_BomberAttack)
REGISTER_STATE(NPC_State_BomberRetreat)
REGISTER_STATE(NPC_State_Reaction)
REGISTER_STATE(NPC_State_EnemyBatReaction)


// Add Some Other Controller States Below...
//REGISTER_STATE(Player_State_Idle)