#pragma once

// DO NOT CHANGE ORDER OF CANVAS TYPE
enum class CanvasType
{
	CANVAS_MAIN_MENU,
	CANVAS_PAUSE,
	CANVAS_OPTION,
	CANVAS_CONTROLS,
	CANVAS_SOUNDS,
	CANVAS_LOSE,
	CANVAS_CREDITS,	
	CANVAS_SHOP,
	CANVAS_POWERUPSCREEN,

	CANVAS_NUM
};