#pragma once

// DO NOT CHANGE ORDER OF CANVAS TYPE
enum class CanvasType
{
	CANVAS_MAIN_MENU,
	CANVAS_PAUSE,
	CANVAS_OPTION,
	CANVAS_CONTROLS,
	CANVAS_SOUNDS,
	CANVAS_LOSE,
	CANVAS_CREDITS,	
	CANVAS_SHOP,
	CANVAS_POWERUPSCREEN,
	CANVAS_VIDEO,
	CANVAS_PROMPT_QUIT,
	CANVAS_PROMPT_RESTART,
	CANVAS_PROMPT_MAIN_QUIT,
	CANVAS_PROMPT_PAUSE2MAIN,

	CANVAS_NUM
};